# Generated by Django 4.2.16 on 2024-11-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_remove_user_refresh_token_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
