# Generated by Django 4.2.16 on 2024-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
