# Generated by Django 4.2.16 on 2024-11-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_url',
        ),
    ]
