# Generated by Django 4.2.16 on 2024-11-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_rename_image_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
